export {useAuth, useVideo} from "../context";
export {
  addNewPlayList,
  addToLikes,
  setWatchedVideos,
  addToPlayList,
  isInWatchedVideos,
  isLiked,
  removeFromLikes,
  removeFromPlayList,
  increaseLikes,
  decreaseLikes,
  getPlayListFirstVideo,
  getAllVideos,
  isInPlayList,
  closePlayList,
  isLikedVideo,
  getVideoPage,
  playlistHandler,
  addToWatchedVideos,
  getAllVideosHome,
} from "../utils";
