const videos = [
    {
      videoId: "4ZmzThsytKU",
      title: "Awesome Food Compilation | Tasty Food Videos",
      views: "598268",
      timestamp: "11 Dec 2020",
      length: "10:15",
      like: "false",
      totalLikes: 8800,
      channelName: "Foodie",
      playlist: [],
      uploadDate: new Date(2021,3,1),
    },
    {
      videoId: "5-IHcF1WnXo",
      title: "6 Delicious Movie Night Snack Recipes",
      views: "839508",
      timestamp: "18 Oct 2020",
      length: "8:15",
      like: "false",
      totalLikes: 15000,
      channelName: "Twisted",
      playlist: [],
      uploadDate: new Date(2021,3,1),
    },
    {
      videoId: "oyfVyYZbOYw",
      title:
        "24 Simple Yet Delicious Breakfast Ideas || 5-Minute Breakfast Recipes",
      views: "3258928",
      timestamp: "18 Oct 2020",
      length: "15:53",
      like: "false",
      totalLikes: 52000,
      channelName: "5-Minute-Craft",
      playlist: [],
      uploadDate: new Date(2020,6,4),
    },
    {
      videoId: "MuajFTgkoHw",
      title: "Quick & Simple Breakfast Recipes With Gordon Ramsay",
      views: "16245378",
      timestamp: "14 May 2020",
      length: "12:48",
      like: "false",
      totalLikes: 438000,
      channelName: "Gordon Ramsay",
      playlist: [],
      uploadDate: new Date(2020,4,14),
    },
    {
      videoId: "X_qo3lnRS1k",
      title: "Gordon's Quick & Simple Dinner Recipes | Gordon Ramsay",
      views: "12797861",
      timestamp: "14 May 2020",
      length: "19:10",
      like: "false",
      totalLikes: 224000,
      channelName: "Gordon Ramsay",
      playlist: [],
      uploadDate: new Date(2020,5,11),
    },
    {
      videoId: "L0AL9HdNQTg",
      title:
        "25 Delicious Food Frying Ideas || Genius Hacks For Cheese And Pizza Lovers!",
      views: "206441",
      timestamp: "14 May 2020",
      length: "13:17",
      like: "false",
      totalLikes: 36000,
      channelName: "5-Minutes Recipes",
      playlist: [],
      uploadDate: new Date(2021,02,28),
    },
    {
      videoId: "NH9K4_2etF8",
      title: "Top 10 Insane Breakfast Recipes",
      views: "1233009",
      timestamp: "25 Jul 2020",
      length: "14:43",
      like: "false",
      totalLikes: 23000,
      channelName: "Twisted",
      playlist: [],
      uploadDate: new Date(2020,5,25),
    },
  ];

  module.exports = videos;